# Generated by Django 4.1.7 on 2023-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='place_bids',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.bid'),
        ),
    ]
