# Generated by Django 4.2.3 on 2023-07-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
    ]
