# Generated by Django 4.1.7 on 2023-03-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_place_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='place_bids',
        ),
        migrations.AddField(
            model_name='auction',
            name='place_bids',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.bid'),
        ),
    ]
