# Generated by Django 4.1.7 on 2023-03-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_place_bids_auction_place_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
