# Generated by Django 4.2.3 on 2023-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='closed',
            new_name='is_closed',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
