# Generated by Django 4.1.7 on 2023-03-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_user_bid_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
