# Generated by Django 4.1.7 on 2023-03-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_user_bid_bidder'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('owner', 'item'), name='unique_user_item_comment'),
        ),
    ]
