# Generated by Django 4.1.7 on 2023-03-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_unique_user_item_comment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_user_item_comment',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('user', 'auction'), name='unique_user_auction_comment'),
        ),
    ]
