# Generated by Django 4.1.7 on 2023-03-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_category_options_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='users',
            new_name='user',
        ),
    ]
